-- ============================================================================
-- SAHE - Conceptos
--   Crea DVSAHET16_CONCEPTOS con el modelo de DVSAHET12_TIPOCOMPENSACION.
--
-- Diferencias con el origen BNSAHET16_CONCEPTOS:
--
--   (no existía)        ->  T16_ID
--       Llave sustituta con identidad. El origen se identificaba por concepto
--       + secuencia.
--
--   T16_ESTADOREGISTRO  ->  T16_CACCION
--       Guarda I, U y D, que son acciones y no estados.
--
--   (no existía)        ->  T16_CESTADOREGISTRO
--       'A' mientras la fila es la vigente; 'I' cuando se cierra.
--
--   T16_ESTADOFUNCIONAL se mantiene: es el Activo/Inactivo que ve el usuario.
--
-- El código del concepto es lo que identifica al concepto para el negocio y
-- es lo que referencia T17, así que lleva un único parcial sobre las filas
-- activas: dos conceptos vigentes no pueden compartir código.
-- ============================================================================

@D:\DValenzuela\Desarrollo\BN\Repositorio\Claude\FuentesSAHE\BaseDatos\conn_sahe.sql

set linesize 200
set pagesize 100
set feedback on
whenever sqlerror exit failure rollback

create table DVSAHET16_CONCEPTOS (
    T16_ID              number generated by default as identity minvalue 1 increment by 1 start with 1 not null,
    T16_CCONCEPTO       varchar2(8)   not null,
    T16_SECUENCIA       number        not null,
    T16_FINIEFECTIVA    date          default sysdate not null,
    T16_FFINEFECTIVA    date          default date '9999-12-31' not null,
    T16_DESCRIPCION     varchar2(255) not null,
    T16_ESTADOFUNCIONAL varchar2(1)   default 'A' not null,
    T16_CACCION         char(1)       default 'I' not null,
    T16_CESTADOREGISTRO char(1)       default 'A' not null,
    T16_CREADOPOR       varchar2(99)  not null,
    T16_FCREACION       date          default sysdate not null,
    T16_ACTUALIZADOPOR  varchar2(99)  default 'SYSTEM' not null,
    T16_FACTUALIZACION  date          default date '9999-12-31' not null,
    T16_COMPUTERID      varchar2(99)  not null,
    T16_LOGINID         varchar2(99)  not null,
    constraint BNPK_T16  primary key (T16_ID),
    constraint CHK_T1601 check (T16_CACCION in ('I','U','D')),
    constraint CHK_T1602 check (T16_CESTADOREGISTRO in ('A','I')),
    constraint CHK_T1603 check (T16_FFINEFECTIVA > T16_FINIEFECTIVA),
    constraint CHK_T1604 check (T16_ESTADOFUNCIONAL in ('A','I'))
);

create index IDX_T1601 on DVSAHET16_CONCEPTOS (T16_CESTADOREGISTRO);

-- Solo indexa las filas activas: las versiones históricas repiten el código.
create unique index UNQ_T1601 on DVSAHET16_CONCEPTOS (
    case when T16_CESTADOREGISTRO = 'A' then T16_CCONCEPTO end
);

comment on table  DVSAHET16_CONCEPTOS                     is 'Conceptos de pago que se asignan a los trabajadores.';
comment on column DVSAHET16_CONCEPTOS.T16_CCONCEPTO       is 'Código del concepto. Es lo que referencia DVSAHET17.';
comment on column DVSAHET16_CONCEPTOS.T16_ESTADOFUNCIONAL is 'Activo/Inactivo que ve el usuario.';
comment on column DVSAHET16_CONCEPTOS.T16_CACCION         is 'Movimiento que creó la fila: I, U o D.';
comment on column DVSAHET16_CONCEPTOS.T16_CESTADOREGISTRO is 'A mientras la fila es la vigente; I cuando se cierra.';

prompt ===== TABLA CREADA =====
select count(*) as columnas from user_tab_columns where table_name = 'DVSAHET16_CONCEPTOS';
exit
