-- ============================================================================
-- SAHE - Concepto por Trabajador
--   Crea DVSAHET17_CONCEPTOXTRABAJADOR con el modelo de
--   DVSAHET12_TIPOCOMPENSACION.
--
-- Diferencias con el origen BNSAHET17_CONCEPTOXTRABAJADOR:
--
--   (no existía)        ->  T17_ID
--       Llave sustituta con identidad.
--
--   T16_CCONCEPTO + T16_SECUENCIA  ->  T17_CCONCEPTO
--       El origen apuntaba a UNA VERSIÓN del concepto (código + secuencia).
--       Aquí se guarda solo el código y NO el T16_ID, a propósito: cada vez
--       que se modifica un concepto se inserta una fila nueva con id nuevo,
--       así que una referencia por id quedaría colgando en cada edición. El
--       código, en cambio, identifica al concepto a lo largo de sus versiones,
--       y UNQ_T1601 garantiza que solo haya un concepto vigente por código.
--
--   T17_ESTADOREGISTRO  ->  T17_CACCION
--   (no existía)        ->  T17_CESTADOREGISTRO
--   (no existía)        ->  T17_ESTADOFUNCIONAL
--       Igual que en T05: el concepto de estado funcional no existía en el
--       origen, así que la migración lo deja en 'A'.
--
--   T17_IMPORTEANTERIOR y T17_FCAMBIO se mantienen: son el rastro del último
--       cambio de importe, que el negocio consulta.
-- ============================================================================

@D:\DValenzuela\Desarrollo\BN\Repositorio\Claude\FuentesSAHE\BaseDatos\conn_sahe.sql

set linesize 200
set pagesize 100
set feedback on
whenever sqlerror exit failure rollback

create table DVSAHET17_CONCEPTOXTRABAJADOR (
    T17_ID              number generated by default as identity minvalue 1 increment by 1 start with 1 not null,
    T17_CTRABAJADOR     varchar2(10)  not null,
    T17_SECUENCIA       number        not null,
    T17_CCONCEPTO       varchar2(8)   not null,
    T17_FINIEFECTIVA    date          default sysdate not null,
    T17_FFINEFECTIVA    date          default date '9999-12-31' not null,
    T17_IMPORTE         number        default 0 not null,
    T17_IMPORTEANTERIOR number        default 0 not null,
    T17_FCAMBIO         date          default sysdate not null,
    T17_ESTADOFUNCIONAL varchar2(1)   default 'A' not null,
    T17_CACCION         char(1)       default 'I' not null,
    T17_CESTADOREGISTRO char(1)       default 'A' not null,
    T17_CREADOPOR       varchar2(99)  not null,
    T17_FCREACION       date          default sysdate not null,
    T17_ACTUALIZADOPOR  varchar2(99)  default 'SYSTEM' not null,
    T17_FACTUALIZACION  date          default date '9999-12-31' not null,
    T17_COMPUTERID      varchar2(99)  not null,
    T17_LOGINID         varchar2(99)  not null,
    constraint BNPK_T17  primary key (T17_ID),
    constraint CHK_T1701 check (T17_CACCION in ('I','U','D')),
    constraint CHK_T1702 check (T17_CESTADOREGISTRO in ('A','I')),
    constraint CHK_T1703 check (T17_FFINEFECTIVA > T17_FINIEFECTIVA),
    constraint CHK_T1704 check (T17_ESTADOFUNCIONAL in ('A','I')),
    constraint CHK_T1705 check (T17_IMPORTE >= 0)
);

-- La pantalla busca por trabajador, no recorre la tabla: son 35 mil filas
-- activas y sin este índice cada consulta sería un full scan.
create index IDX_T1701 on DVSAHET17_CONCEPTOXTRABAJADOR (T17_CTRABAJADOR, T17_CESTADOREGISTRO);
create index IDX_T1702 on DVSAHET17_CONCEPTOXTRABAJADOR (T17_CCONCEPTO, T17_CESTADOREGISTRO);

-- Un trabajador no puede tener el mismo concepto dos veces vigente.
create unique index UNQ_T1701 on DVSAHET17_CONCEPTOXTRABAJADOR (
    case when T17_CESTADOREGISTRO = 'A' then T17_CTRABAJADOR end,
    case when T17_CESTADOREGISTRO = 'A' then T17_CCONCEPTO   end
);

comment on table  DVSAHET17_CONCEPTOXTRABAJADOR                     is 'Importe de cada concepto asignado a un trabajador.';
comment on column DVSAHET17_CONCEPTOXTRABAJADOR.T17_CCONCEPTO       is 'Código del concepto en DVSAHET16. Se guarda el código y no el id porque el id cambia con cada versión del concepto.';
comment on column DVSAHET17_CONCEPTOXTRABAJADOR.T17_IMPORTEANTERIOR is 'Importe que tenía antes del último cambio.';
comment on column DVSAHET17_CONCEPTOXTRABAJADOR.T17_FCAMBIO         is 'Cuándo cambió el importe por última vez.';

prompt ===== TABLA CREADA =====
select count(*) as columnas from user_tab_columns where table_name = 'DVSAHET17_CONCEPTOXTRABAJADOR';
exit
