-- ============================================================================
-- SAHE - Excepción por Puesto
--   Crea DVSAHET05_EXCEPCIONXPUESTO con el mismo modelo que
--   DVSAHET12_TIPOCOMPENSACION: llave sustituta con identidad, vigencia por
--   fechas, acción del movimiento y estado del registro separados.
--
-- Diferencias con el origen BNSAHET05_EXCEPCIONXPUESTO:
--
--   (no existía)  ->  T05_ID
--       Llave sustituta. El origen se identificaba por puesto + secuencia,
--       que obliga a arrastrar dos columnas en cada llamada.
--
--   T05_ESTADOREGISTRO  ->  T05_CACCION
--       La columna anterior guarda I, U y D, que son acciones y no estados.
--
--   (no existía)  ->  T05_CESTADOREGISTRO
--       'A' mientras la fila es la vigente; 'I' cuando se cierra.
--
--   (no existía)  ->  T05_ESTADOFUNCIONAL
--       El Activo/Inactivo que ve el usuario, distinto del estado del
--       registro. En T12 venía del origen; aquí no existía, así que la
--       migración lo deja en 'A' para todas las filas.
--
-- Se ejecuta una sola vez. Volver a correrlo da ORA-00955.
-- ============================================================================

@D:\DValenzuela\Desarrollo\BN\Repositorio\Claude\FuentesSAHE\BaseDatos\conn_sahe.sql

set linesize 200
set pagesize 100
set feedback on
whenever sqlerror exit failure rollback

create table DVSAHET05_EXCEPCIONXPUESTO (
    T05_ID              number generated by default as identity minvalue 1 increment by 1 start with 1 not null,
    T05_CPUESTO         varchar2(60)  not null,
    T05_SECUENCIA       number        not null,
    T05_FINIEFECTIVA    date          default sysdate not null,
    T05_FFINEFECTIVA    date          default date '9999-12-31' not null,
    T05_CLUGARTRABAJO   varchar2(5)   not null,
    T05_ESTADOFUNCIONAL varchar2(1)   default 'A' not null,
    T05_CACCION         char(1)       default 'I' not null,
    T05_CESTADOREGISTRO char(1)       default 'A' not null,
    T05_CREADOPOR       varchar2(50)  not null,
    T05_FCREACION       date          default sysdate not null,
    T05_ACTUALIZADOPOR  varchar2(50)  default 'SYSTEM' not null,
    T05_FACTUALIZACION  date          default date '9999-12-31' not null,
    T05_COMPUTERID      varchar2(50)  not null,
    T05_LOGINID         varchar2(50)  not null,
    constraint BNPK_T05  primary key (T05_ID),
    constraint CHK_T0501 check (T05_CACCION in ('I','U','D')),
    constraint CHK_T0502 check (T05_CESTADOREGISTRO in ('A','I')),
    constraint CHK_T0503 check (T05_FFINEFECTIVA > T05_FINIEFECTIVA),
    constraint CHK_T0504 check (T05_ESTADOFUNCIONAL in ('A','I'))
);

-- La pantalla siempre filtra por el estado del registro; sin este índice cada
-- carga recorre la tabla entera.
create index IDX_T0501 on DVSAHET05_EXCEPCIONXPUESTO (T05_CESTADOREGISTRO);

-- Un puesto no puede tener dos excepciones vigentes a la vez. El índice es
-- función: solo indexa las filas activas, así las versiones históricas -que
-- repiten puesto y lugar- no chocan.
create unique index UNQ_T0501 on DVSAHET05_EXCEPCIONXPUESTO (
    case when T05_CESTADOREGISTRO = 'A' then T05_CPUESTO       end,
    case when T05_CESTADOREGISTRO = 'A' then T05_CLUGARTRABAJO end
);

comment on table  DVSAHET05_EXCEPCIONXPUESTO                     is 'Puestos exceptuados del control de horas extra, por lugar de trabajo.';
comment on column DVSAHET05_EXCEPCIONXPUESTO.T05_CPUESTO         is 'Código del puesto. Se busca en BN_BN_HR_VI_SAHE_PUESTO.';
comment on column DVSAHET05_EXCEPCIONXPUESTO.T05_CLUGARTRABAJO   is 'Código del lugar de trabajo. Catálogo BN_BN_HR_VI_SAHE_LUGARTRABAJO.';
comment on column DVSAHET05_EXCEPCIONXPUESTO.T05_ESTADOFUNCIONAL is 'Activo/Inactivo que ve el usuario.';
comment on column DVSAHET05_EXCEPCIONXPUESTO.T05_CACCION         is 'Movimiento que creó la fila: I, U o D.';
comment on column DVSAHET05_EXCEPCIONXPUESTO.T05_CESTADOREGISTRO is 'A mientras la fila es la vigente; I cuando se cierra.';

prompt ===== TABLA CREADA =====
select column_id, column_name, data_type, nullable
  from user_tab_columns where table_name = 'DVSAHET05_EXCEPCIONXPUESTO' order by column_id;

exit
