-- ============================================================================
-- SAHE - Migración de Parámetros Generales
--   Origen  : BNSAHET07_PARAMETROSGEN   (190 filas, modelo anterior)
--   Destino : DVSAHET07_PARAMETROSGEN   (modelo nuevo)
--
-- Equivalencias que NO son 1 a 1:
--
--   T07_ESTADOREGISTRO  ->  T07_CACCION
--       La columna anterior guardaba I/U, que son acciones y no estados; el
--       modelo nuevo las separa en T07_CACCION (I,U,D) y T07_CESTADOREGISTRO
--       (A,I). El contenido pasa tal cual a la acción.
--
--   (no existía)        ->  T07_CESTADOREGISTRO
--       Se deriva de la vigencia: 'A' para la fila vigente
--       (T07_FFINEFECTIVA = 31/12/9999) e 'I' para las versiones cerradas.
--       Es una regla asumida; si el criterio es otro se corrige con un UPDATE.
--
--   T07_JORLABEXCLUHE   ->  (no existe en el destino)
--       Se pierde. 37 filas traen códigos reales (PA02,PA03,INF7,LHR3 y
--       similares), 15 traen un espacio y 138 vienen nulas.
--
-- T07_ID es IDENTITY BY DEFAULT en el destino, así que admite el id explícito;
-- al final se reposiciona la secuencia para que el próximo alta siga en 191.
-- ============================================================================

@D:\DValenzuela\Desarrollo\BN\Repositorio\Claude\FuentesSAHE\BaseDatos\conn_sahe.sql

set linesize 200
set pagesize 100
set feedback on
whenever sqlerror exit failure rollback

prompt ===== ANTES DE MIGRAR =====
select (select count(*) from BNSAHET07_PARAMETROSGEN) as origen,
       (select count(*) from DVSAHET07_PARAMETROSGEN) as destino
  from dual;

prompt ===== MIGRANDO =====
insert into DVSAHET07_PARAMETROSGEN (
       T07_ID,
       T07_FINIEFECTIVA,
       T07_FFINEFECTIVA,
       T07_MULTIPLOCONTEOHE,
       T07_INICIOCONTEOHE,
       T07_FINCONTEOHE,
       T07_PLAZOMAXREGISTROHE,
       T07_DIAFINALAPROBAR,
       T07_CANTIDADDIASMINIMOSOL,
       T07_DIRECTIVA,
       T07_MANUAL,
       T07_CACCION,
       T07_CESTADOREGISTRO,
       T07_CREADOPOR,
       T07_FCREACION,
       T07_ACTUALIZADOPOR,
       T07_FACTUALIZACION,
       T07_COMPUTERID,
       T07_LOGINID)
select o.T07_ID,
       o.T07_FINIEFECTIVA,
       o.T07_FFINEFECTIVA,
       o.T07_MULTIPLOCONTEOHE,
       o.T07_INICIOCONTEOHE,
       o.T07_FINCONTEOHE,
       o.T07_PLAZOMAXREGISTROHE,
       o.T07_DIAFINALAPROBAR,
       o.T07_CANTIDADDIASMINIMOSOL,
       o.T07_DIRECTIVA,
       o.T07_MANUAL,
       o.T07_ESTADOREGISTRO,
       case when o.T07_FFINEFECTIVA >= to_date('31/12/9999','DD/MM/YYYY')
            then 'A' else 'I' end,
       o.T07_CREADOPOR,
       o.T07_FCREACION,
       o.T07_ACTUALIZADOPOR,
       o.T07_FACTUALIZACION,
       o.T07_COMPUTERID,
       o.T07_LOGINID
  from BNSAHET07_PARAMETROSGEN o;

commit;

prompt ===== REPOSICIONANDO LA IDENTIDAD =====
alter table DVSAHET07_PARAMETROSGEN
      modify (T07_ID generated by default as identity (start with limit value));

prompt ===== DESPUES DE MIGRAR =====
select (select count(*) from BNSAHET07_PARAMETROSGEN) as origen,
       (select count(*) from DVSAHET07_PARAMETROSGEN) as destino,
       (select count(*) from DVSAHET07_PARAMETROSGEN where T07_CESTADOREGISTRO = 'A') as vigentes
  from dual;

prompt ===== ACCIONES MIGRADAS =====
select T07_CACCION as accion, T07_CESTADOREGISTRO as estado, count(*) as filas
  from DVSAHET07_PARAMETROSGEN
 group by T07_CACCION, T07_CESTADOREGISTRO
 order by 1, 2;

prompt ===== FILA VIGENTE EN EL DESTINO =====
select T07_ID, T07_MULTIPLOCONTEOHE as multiplo, T07_INICIOCONTEOHE as ini,
       T07_FINCONTEOHE as fin, T07_CANTIDADDIASMINIMOSOL as plazo_min,
       T07_PLAZOMAXREGISTROHE as plazo_max, T07_DIAFINALAPROBAR as dia_aprob,
       T07_CACCION as accion, T07_CESTADOREGISTRO as estado
  from DVSAHET07_PARAMETROSGEN
 where T07_CESTADOREGISTRO = 'A';

exit
